### ISSUE TITLE
It seems that the master branch has a little problem in Travis-CI building process.

### ISSUE THREAD

**Issue by liukgg** [mfornos/awesome-microservices#145]
It seems that the master branch has a little problem in Travis-CI building process, because most pull requests created recently have encoutered the same problem when building in Travis-CI:
"The command "awesome_bot README.md --allow-redirect --allow-ssl" exited with 1."
For example:
https://github.com/mfornos/awesome-microservices/pull/144
https://github.com/mfornos/awesome-microservices/pull/143

**Comment by taik0** [comment]
I sent a PR #140 to fix problem links so #139 was able to merge, but now it's failing again :(

**Comment by liukgg** [comment]
Is this project still being maintained?
