### ISSUE TITLE
api gateway aggregation

### ISSUE THREAD

**Issue by hoswey** [mfornos/awesome-microservices#70]
I am sorry this may not a issue.
From the [microserivce.io](http://microservices.io/patterns/apigateway.html),  there is a open question that how to expose the service, is there anything tool?  is it like [falcor](https://github.com/Netflix/falcor) or [GrapHQL](http://graphql.org/learn/)?

**Comment by mfornos** [comment]
For this kind of communication feel free to send me a private e-mail.

Thank you! :smile_cat:
