### ISSUE TITLE
New section about architecture benchmark

### ISSUE THREAD

**Issue by cmendesce** [mfornos/awesome-microservices#72]
Hi all, 

What do you think about a section listing some benchmark that may be useful in testing microservices related tools or serving as an architecture inspiration? These are some options: 
- [Spring Boot Graph Processing](https://github.com/kbastani/spring-boot-graph-processing-example)
- [Microservices Demo](https://github.com/microservices-demo)

May there are a lot of hidden alternatives like these that the community should meet.

**Comment by mfornos** [comment]
Great idea.

The provided examples to me are more blueprints or "reference implementations" like the mythical Pet Store, whose primary use might not be benchmarking. Not sure if architecture benchmark is the most accurate naming.

If you have a clear vision on what content would include the new "architecture benchmark" (or other name, maybe?) section, please proceed.

:smiley_cat:

**Comment by mfornos** [comment]
This project could serve as an example: https://github.com/sczyh30/vertx-blueprint-microservice
